apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: basic-example-vn
spec:
  resourceGroupNameRef:
    name: basic-example-rg
  location: West US 2
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
          #  - 10.3.0.0/16
  providerConfigRef:
    name:  default