apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: c81b45a2-2706-4c80-9d4d-ee73500d6667
  subscriptionID: d3fc4979-9536-42c0-82d0-24800e05df25
  tenantID: 86c552a6-affa-4e4b-b652-a3be228075fb