#apiVersion: azure.crossplane.io/v1alpha3
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: example-rg
spec:
  location: West US 2
  providerConfigRef:
    name: example
---
#apiVersion: database.azure.crossplane.io/v1beta1
apiVersion: database.azure.upbound.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: example-psql
  labels:
    example: "true"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: example-rg
    location: West US 2
    minimalTlsVersion: TLS1_2
    sslEnforcement: Enabled
    version: "9.6"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-psql
  providerConfigRef:
    name: default
---
#apiVersion: database.azure.crossplane.io/v1beta1
apiVersion: database.azure.upbound.io/v1beta1
kind: PostgreSQLServerConfiguration
metadata:
  name: example-psql-configuration
spec:
  providerConfigRef:
    name: default
  forProvider:
    resourceGroupNameRef:
      name: example-rg
    serverNameRef:
      name: example-psql
    name: max_wal_senders
    value: "12"